###
POST http://localhost/Usuarios/autenticar
Content-Type: application/json

{
    "nombreDelUsuario": "cisco",
    "claveDelUsuario": "$2b$10$82udm6lgk7ItzZ7hb2Jt10hkVrOc.IWLHdjZEQui9ydAGQNDLaFiq"
}
###

GET http://localhost/Usuarios/ HTTP/1.1
//Authorization: Bearer 
###

GET http://localhost/Programaciones/ HTTP/1.1

###

GET http://localhost/Servicios/ HTTP/1.1

###

GET http://localhost/Solicitantes/ HTTP/1.1

###

GET http://localhost/Solicitudes/ HTTP/1.1

###

GET http://localhost/Usuarios/ HTTP/1.1

###

GET http://localhost/Programaciones/1 HTTP/1.1

###

GET http://localhost/Servicios/1 HTTP/1.1

###

GET http://localhost/Solicitantes/1 HTTP/1.1

###

GET http://localhost/Solicitudes/1 HTTP/1.1

###

GET http://localhost/Usuarios/1 HTTP/1.1

###

POST http://localhost/Programaciones HTTP/1.1


###

POST  http://localhost/Servicios HTTP/1.1


###

POST  http://localhost/Solicitantes HTTP/1.1


###

POST  http://localhost/Solicitudes HTTP/1.1


###

POST  http://localhost/Usuarios HTTP/1.1


###

DELETE  http://localhost/Programaciones/10 HTTP/1.1
###

DELETE http://localhost/Servicios/10 HTTP/1.1
###

DELETE http://localhost/Solicitantes/ HTTP/1.1
###

DELETE http://localhost/Solicitudes/10 HTTP/1.1
###

DELETE http://localhost/Usuarios/ HTTP/1.1

###

PUT  http://localhost/Programaciones/1 HTTP/1.1


###

PUT  http://localhost/Servicios/1 HTTP/1.1


###

PUT  http://localhost/Solicitantes/1 HTTP/1.1
Content-Type: application/json


###

PUT  http://localhost/Solicitudes/1 HTTP/1.1


###

PUT  http://localhost/Usuarios/1 HTTP/1.1
###